// Auto-generated. Do not edit!

// (in-package entrada_acciones_mensajes.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class ContadorGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.objetivo = null;
    }
    else {
      if (initObj.hasOwnProperty('objetivo')) {
        this.objetivo = initObj.objetivo
      }
      else {
        this.objetivo = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type ContadorGoal
    // Serialize message field [objetivo]
    bufferOffset = _serializer.int64(obj.objetivo, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type ContadorGoal
    let len;
    let data = new ContadorGoal(null);
    // Deserialize message field [objetivo]
    data.objetivo = _deserializer.int64(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 8;
  }

  static datatype() {
    // Returns string type for a message object
    return 'entrada_acciones_mensajes/ContadorGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '3f78b7147b70bba3a1b96bd9bc633cfc';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #goal
    int64 objetivo
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new ContadorGoal(null);
    if (msg.objetivo !== undefined) {
      resolved.objetivo = msg.objetivo;
    }
    else {
      resolved.objetivo = 0
    }

    return resolved;
    }
};

module.exports = ContadorGoal;
