// Generated by gencpp from file entrada_acciones_mensajes/ContadorGoal.msg
// DO NOT EDIT!


#ifndef ENTRADA_ACCIONES_MENSAJES_MESSAGE_CONTADORGOAL_H
#define ENTRADA_ACCIONES_MENSAJES_MESSAGE_CONTADORGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace entrada_acciones_mensajes
{
template <class ContainerAllocator>
struct ContadorGoal_
{
  typedef ContadorGoal_<ContainerAllocator> Type;

  ContadorGoal_()
    : objetivo(0)  {
    }
  ContadorGoal_(const ContainerAllocator& _alloc)
    : objetivo(0)  {
  (void)_alloc;
    }



   typedef int64_t _objetivo_type;
  _objetivo_type objetivo;





  typedef boost::shared_ptr< ::entrada_acciones_mensajes::ContadorGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::entrada_acciones_mensajes::ContadorGoal_<ContainerAllocator> const> ConstPtr;

}; // struct ContadorGoal_

typedef ::entrada_acciones_mensajes::ContadorGoal_<std::allocator<void> > ContadorGoal;

typedef boost::shared_ptr< ::entrada_acciones_mensajes::ContadorGoal > ContadorGoalPtr;
typedef boost::shared_ptr< ::entrada_acciones_mensajes::ContadorGoal const> ContadorGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::entrada_acciones_mensajes::ContadorGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::entrada_acciones_mensajes::ContadorGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::entrada_acciones_mensajes::ContadorGoal_<ContainerAllocator1> & lhs, const ::entrada_acciones_mensajes::ContadorGoal_<ContainerAllocator2> & rhs)
{
  return lhs.objetivo == rhs.objetivo;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::entrada_acciones_mensajes::ContadorGoal_<ContainerAllocator1> & lhs, const ::entrada_acciones_mensajes::ContadorGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace entrada_acciones_mensajes

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::entrada_acciones_mensajes::ContadorGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::entrada_acciones_mensajes::ContadorGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::entrada_acciones_mensajes::ContadorGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::entrada_acciones_mensajes::ContadorGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::entrada_acciones_mensajes::ContadorGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::entrada_acciones_mensajes::ContadorGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::entrada_acciones_mensajes::ContadorGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3f78b7147b70bba3a1b96bd9bc633cfc";
  }

  static const char* value(const ::entrada_acciones_mensajes::ContadorGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3f78b7147b70bba3ULL;
  static const uint64_t static_value2 = 0xa1b96bd9bc633cfcULL;
};

template<class ContainerAllocator>
struct DataType< ::entrada_acciones_mensajes::ContadorGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "entrada_acciones_mensajes/ContadorGoal";
  }

  static const char* value(const ::entrada_acciones_mensajes::ContadorGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::entrada_acciones_mensajes::ContadorGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#goal\n"
"int64 objetivo\n"
;
  }

  static const char* value(const ::entrada_acciones_mensajes::ContadorGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::entrada_acciones_mensajes::ContadorGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.objetivo);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ContadorGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::entrada_acciones_mensajes::ContadorGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::entrada_acciones_mensajes::ContadorGoal_<ContainerAllocator>& v)
  {
    s << indent << "objetivo: ";
    Printer<int64_t>::stream(s, indent + "  ", v.objetivo);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ENTRADA_ACCIONES_MENSAJES_MESSAGE_CONTADORGOAL_H
