// Generated by gencpp from file entrada_acciones_mensajes/ContadorFeedback.msg
// DO NOT EDIT!


#ifndef ENTRADA_ACCIONES_MENSAJES_MESSAGE_CONTADORFEEDBACK_H
#define ENTRADA_ACCIONES_MENSAJES_MESSAGE_CONTADORFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace entrada_acciones_mensajes
{
template <class ContainerAllocator>
struct ContadorFeedback_
{
  typedef ContadorFeedback_<ContainerAllocator> Type;

  ContadorFeedback_()
    : proporcion(0.0)  {
    }
  ContadorFeedback_(const ContainerAllocator& _alloc)
    : proporcion(0.0)  {
  (void)_alloc;
    }



   typedef double _proporcion_type;
  _proporcion_type proporcion;





  typedef boost::shared_ptr< ::entrada_acciones_mensajes::ContadorFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::entrada_acciones_mensajes::ContadorFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct ContadorFeedback_

typedef ::entrada_acciones_mensajes::ContadorFeedback_<std::allocator<void> > ContadorFeedback;

typedef boost::shared_ptr< ::entrada_acciones_mensajes::ContadorFeedback > ContadorFeedbackPtr;
typedef boost::shared_ptr< ::entrada_acciones_mensajes::ContadorFeedback const> ContadorFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::entrada_acciones_mensajes::ContadorFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::entrada_acciones_mensajes::ContadorFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::entrada_acciones_mensajes::ContadorFeedback_<ContainerAllocator1> & lhs, const ::entrada_acciones_mensajes::ContadorFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.proporcion == rhs.proporcion;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::entrada_acciones_mensajes::ContadorFeedback_<ContainerAllocator1> & lhs, const ::entrada_acciones_mensajes::ContadorFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace entrada_acciones_mensajes

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::entrada_acciones_mensajes::ContadorFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::entrada_acciones_mensajes::ContadorFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::entrada_acciones_mensajes::ContadorFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::entrada_acciones_mensajes::ContadorFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::entrada_acciones_mensajes::ContadorFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::entrada_acciones_mensajes::ContadorFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::entrada_acciones_mensajes::ContadorFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "acf9f26d7e37f60263756432c9301e69";
  }

  static const char* value(const ::entrada_acciones_mensajes::ContadorFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xacf9f26d7e37f602ULL;
  static const uint64_t static_value2 = 0x63756432c9301e69ULL;
};

template<class ContainerAllocator>
struct DataType< ::entrada_acciones_mensajes::ContadorFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "entrada_acciones_mensajes/ContadorFeedback";
  }

  static const char* value(const ::entrada_acciones_mensajes::ContadorFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::entrada_acciones_mensajes::ContadorFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#feedback\n"
"float64 proporcion\n"
;
  }

  static const char* value(const ::entrada_acciones_mensajes::ContadorFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::entrada_acciones_mensajes::ContadorFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.proporcion);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ContadorFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::entrada_acciones_mensajes::ContadorFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::entrada_acciones_mensajes::ContadorFeedback_<ContainerAllocator>& v)
  {
    s << indent << "proporcion: ";
    Printer<double>::stream(s, indent + "  ", v.proporcion);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ENTRADA_ACCIONES_MENSAJES_MESSAGE_CONTADORFEEDBACK_H
