(cl:defpackage entrada_acciones_mensajes-msg
  (:use )
  (:export
   "<CONTADORACTION>"
   "CONTADORACTION"
   "<CONTADORACTIONFEEDBACK>"
   "CONTADORACTIONFEEDBACK"
   "<CONTADORACTIONGOAL>"
   "CONTADORACTIONGOAL"
   "<CONTADORACTIONRESULT>"
   "CONTADORACTIONRESULT"
   "<CONTADORFEEDBACK>"
   "CONTADORFEEDBACK"
   "<CONTADORGOAL>"
   "CONTADORGOAL"
   "<CONTADORRESULT>"
   "CONTADORRESULT"
  ))

