; Auto-generated. Do not edit!


(cl:in-package entrada_acciones_mensajes-msg)


;//! \htmlinclude ContadorGoal.msg.html

(cl:defclass <ContadorGoal> (roslisp-msg-protocol:ros-message)
  ((objetivo
    :reader objetivo
    :initarg :objetivo
    :type cl:integer
    :initform 0))
)

(cl:defclass ContadorGoal (<ContadorGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ContadorGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ContadorGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name entrada_acciones_mensajes-msg:<ContadorGoal> is deprecated: use entrada_acciones_mensajes-msg:ContadorGoal instead.")))

(cl:ensure-generic-function 'objetivo-val :lambda-list '(m))
(cl:defmethod objetivo-val ((m <ContadorGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader entrada_acciones_mensajes-msg:objetivo-val is deprecated.  Use entrada_acciones_mensajes-msg:objetivo instead.")
  (objetivo m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ContadorGoal>) ostream)
  "Serializes a message object of type '<ContadorGoal>"
  (cl:let* ((signed (cl:slot-value msg 'objetivo)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 18446744073709551616) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ContadorGoal>) istream)
  "Deserializes a message object of type '<ContadorGoal>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'objetivo) (cl:if (cl:< unsigned 9223372036854775808) unsigned (cl:- unsigned 18446744073709551616))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ContadorGoal>)))
  "Returns string type for a message object of type '<ContadorGoal>"
  "entrada_acciones_mensajes/ContadorGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ContadorGoal)))
  "Returns string type for a message object of type 'ContadorGoal"
  "entrada_acciones_mensajes/ContadorGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ContadorGoal>)))
  "Returns md5sum for a message object of type '<ContadorGoal>"
  "3f78b7147b70bba3a1b96bd9bc633cfc")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ContadorGoal)))
  "Returns md5sum for a message object of type 'ContadorGoal"
  "3f78b7147b70bba3a1b96bd9bc633cfc")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ContadorGoal>)))
  "Returns full string definition for message of type '<ContadorGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal~%int64 objetivo~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ContadorGoal)))
  "Returns full string definition for message of type 'ContadorGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal~%int64 objetivo~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ContadorGoal>))
  (cl:+ 0
     8
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ContadorGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'ContadorGoal
    (cl:cons ':objetivo (objetivo msg))
))
