; Auto-generated. Do not edit!


(cl:in-package entrada_acciones_mensajes-msg)


;//! \htmlinclude ContadorResult.msg.html

(cl:defclass <ContadorResult> (roslisp-msg-protocol:ros-message)
  ((contador
    :reader contador
    :initarg :contador
    :type cl:integer
    :initform 0))
)

(cl:defclass ContadorResult (<ContadorResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ContadorResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ContadorResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name entrada_acciones_mensajes-msg:<ContadorResult> is deprecated: use entrada_acciones_mensajes-msg:ContadorResult instead.")))

(cl:ensure-generic-function 'contador-val :lambda-list '(m))
(cl:defmethod contador-val ((m <ContadorResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader entrada_acciones_mensajes-msg:contador-val is deprecated.  Use entrada_acciones_mensajes-msg:contador instead.")
  (contador m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ContadorResult>) ostream)
  "Serializes a message object of type '<ContadorResult>"
  (cl:let* ((signed (cl:slot-value msg 'contador)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 18446744073709551616) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ContadorResult>) istream)
  "Deserializes a message object of type '<ContadorResult>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'contador) (cl:if (cl:< unsigned 9223372036854775808) unsigned (cl:- unsigned 18446744073709551616))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ContadorResult>)))
  "Returns string type for a message object of type '<ContadorResult>"
  "entrada_acciones_mensajes/ContadorResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ContadorResult)))
  "Returns string type for a message object of type 'ContadorResult"
  "entrada_acciones_mensajes/ContadorResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ContadorResult>)))
  "Returns md5sum for a message object of type '<ContadorResult>"
  "ca8b12a43af0ec7cb0057d704d9bb5ac")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ContadorResult)))
  "Returns md5sum for a message object of type 'ContadorResult"
  "ca8b12a43af0ec7cb0057d704d9bb5ac")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ContadorResult>)))
  "Returns full string definition for message of type '<ContadorResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result~%int64 contador~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ContadorResult)))
  "Returns full string definition for message of type 'ContadorResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result~%int64 contador~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ContadorResult>))
  (cl:+ 0
     8
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ContadorResult>))
  "Converts a ROS message object to a list"
  (cl:list 'ContadorResult
    (cl:cons ':contador (contador msg))
))
