; Auto-generated. Do not edit!


(cl:in-package entrada_acciones_mensajes-msg)


;//! \htmlinclude ContadorFeedback.msg.html

(cl:defclass <ContadorFeedback> (roslisp-msg-protocol:ros-message)
  ((proporcion
    :reader proporcion
    :initarg :proporcion
    :type cl:float
    :initform 0.0))
)

(cl:defclass ContadorFeedback (<ContadorFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ContadorFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ContadorFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name entrada_acciones_mensajes-msg:<ContadorFeedback> is deprecated: use entrada_acciones_mensajes-msg:ContadorFeedback instead.")))

(cl:ensure-generic-function 'proporcion-val :lambda-list '(m))
(cl:defmethod proporcion-val ((m <ContadorFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader entrada_acciones_mensajes-msg:proporcion-val is deprecated.  Use entrada_acciones_mensajes-msg:proporcion instead.")
  (proporcion m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ContadorFeedback>) ostream)
  "Serializes a message object of type '<ContadorFeedback>"
  (cl:let ((bits (roslisp-utils:encode-double-float-bits (cl:slot-value msg 'proporcion))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ContadorFeedback>) istream)
  "Deserializes a message object of type '<ContadorFeedback>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'proporcion) (roslisp-utils:decode-double-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ContadorFeedback>)))
  "Returns string type for a message object of type '<ContadorFeedback>"
  "entrada_acciones_mensajes/ContadorFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ContadorFeedback)))
  "Returns string type for a message object of type 'ContadorFeedback"
  "entrada_acciones_mensajes/ContadorFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ContadorFeedback>)))
  "Returns md5sum for a message object of type '<ContadorFeedback>"
  "acf9f26d7e37f60263756432c9301e69")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ContadorFeedback)))
  "Returns md5sum for a message object of type 'ContadorFeedback"
  "acf9f26d7e37f60263756432c9301e69")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ContadorFeedback>)))
  "Returns full string definition for message of type '<ContadorFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%float64 proporcion~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ContadorFeedback)))
  "Returns full string definition for message of type 'ContadorFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%float64 proporcion~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ContadorFeedback>))
  (cl:+ 0
     8
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ContadorFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'ContadorFeedback
    (cl:cons ':proporcion (proporcion msg))
))
